// ═══════════════════════════════════════════════════════════════
// mockData.js — THIN RE-EXPORT WRAPPER
//
// This file was the original 1980-line monolithic data store.
// It now re-exports everything from the modular data layer at
// src/lib/data/index.js. No consuming component imports need
// to change.
//
// The actual data lives in src/data/*.json, generated by
// scripts/convert_db.py from the production SQLite export.
// ═══════════════════════════════════════════════════════════════

export {
  // --- Arrays ---
  buildings,
  services,
  serviceCategories,
  buildingServices,
  vhes,
  meters,
  activities,
  suppliers,
  supplierCategories,
  distributionMethods,
  distributionModels,
  savedViews,
  ledgerEntries,
  costCategories,
  monthlyCloseStatuses,
  costAttribution,
  moduleConfig,

  // --- Array getter functions (org-aware) ---
  getBuildings,
  getServices,
  getServiceCategories,
  getSupplierCategories,
  getMeters,
  getSavedViews,

  // --- Building getters ---
  getBuilding,
  getBuildingByComplexId,

  // --- Service getters ---
  getService,
  getServiceByCode,
  getServicesByCategory,
  getServicesByCategoryId,
  getCategory,

  // --- Finance getters ---
  getBuildingServices,
  getBuildingServicesByService,
  getBuildingService,
  getBuildingServicesByYear,
  getCostAttributionByVhe,
  getCostCategoriesByService,

  // --- VHE getters ---
  getVhe,
  getVhesByBuilding,

  // --- Meter getters ---
  getMetersByBuilding,
  getMetersByVhe,
  getSubmetersByVhe,
  getVheMeterReadings,

  // --- Ledger getters ---
  getLedgerByService,
  getLedgerByBuilding,
  getLedgerByServiceAndBuilding,
  getLedgerGroupedByCostCategory,
  getLedgerSummaryByService,
  getLedgerSummaryByBuilding,

  // --- Supplier getters ---
  getSupplier,
  getSuppliersByService,
  getSuppliersByCategory,

  // --- Distribution getters ---
  getDistributionMethod,
  getDistributionModel,

  // --- Monthly close getters ---
  getMonthlyCloseForBuilding,
  getMonthlyCloseForBuildingService,
  getMonthlyCloseGridForBuilding,

  // --- View getters ---
  getView,
  getViewsForObject,

  // --- Activity getters ---
  getActivitiesByBuilding,

  // --- Task & note getters ---
  tasks,
  notes,
  getTasksByBuilding,
  getNotesByBuilding,

  // --- Config ---
  isFeatureEnabled,
  getModuleConfig,

  // --- Heating season getters ---
  getHeatingSeasonsByBuilding,
  getHeatingSeasons,

  // --- Distribution model by building ---
  getDistributionModelsByBuilding,

  // --- Org state ---
  setActiveOrg,
  getActiveOrgId,

  // --- Meter links ---
  costCategoryMeterLinks,
  getMeterLink,
  getMeterLinksByBuilding,
  getMeterLinksByService,
  addMeterLink,
  removeMeterLink,

  // --- Field sources ---
  FIELD_SOURCES,
  getFieldSource,
  getEntitySource,

  // --- Distributions ---
  getDistributions,
  getDistributionById,
  getDistributionsByBuilding,
  getDistributionByPeriod,
  getActiveDistribution,
  addRuntimeDistribution,
  buildDistributionFromData,
  STEP_ORDER,
  STEP_CONFIG,
  getStepIndex,
  getFlaggedServiceCount,
} from "./data/index.js";
